### ISSUE TITLE
Image stretched when computationSize < viewSize

### ISSUE THREAD

**Issue by vincurekf** [Easonzero/primitive#1]
There seems to be weird stretching when computation size is lower than view size.
For example I have 512×512 image: 
![test](https://user-images.githubusercontent.com/2306998/50952413-ad8cdb80-14b0-11e9-8305-0e49df3cdb93.png)

When using:
```js
cfg.computationSize = 256;
cfg.viewSize = 512;
```
the image becomes stretched like so:
![test_results_cs256-ws512](https://user-images.githubusercontent.com/2306998/50953305-4290d400-14b3-11e9-99b6-d5211e000338.png)

But in console, everything seems ok, I have added some console.log():
![test_result_cs256-ws512_console](https://user-images.githubusercontent.com/2306998/50952955-38220a80-14b2-11e9-8337-9c8161d22a6f.png)

When using:
```js
cfg.computationSize = 256;
cfg.viewSize = 256;
```
the image renders correct:
![test_results_cs256-ws256](https://user-images.githubusercontent.com/2306998/50953348-63592980-14b3-11e9-8c0d-0af49507124e.png)

Otherwise it works great, thank you!

**Comment by Easonzero** [comment]
I will fix it as soon as possible, but I have not had much time recently. Thanks.
